version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "dgd4f45ds4f5@fds#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - app-network

  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
    networks:
      - app-network

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5342:80"
      - "5341:5341"
    networks:
      - app-network

  web:
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - elasticsearch
      - redis
      - seq
    ports:
      - "8000:80"
    networks:
      - app-network

  consumer:
    build:
      context: ./src/Consumers
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - elasticsearch
      - redis
      - seq
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network: