# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  consumer:
    build:
      context: "D:\\programming\\Projects\\NiceShop\\src\\Consumers"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Consumers.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "consumers:dev"
    ports: []
    volumes:
    - "C:\\Users\\_Amirex_\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\programming\\Projects\\NiceShop\\src\\Consumers:/app:rw"
    - "D:\\programming\\Projects\\NiceShop:/src:rw"
    working_dir: "/app"
  web:
    build:
      context: "D:\\programming\\Projects\\NiceShop\\src\\Web"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/NiceShop.Web.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/NiceShop.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "web:dev"
    ports: []
    volumes:
    - "C:\\Users\\_Amirex_\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\programming\\Projects\\NiceShop\\src\\Web:/app:rw"
    - "D:\\programming\\Projects\\NiceShop:/src:rw"
    working_dir: "/app"
